import { app } from "electron";
import { EventEmitter } from "events";
import fs from "fs/promises";
import path from "path";
import * as dbus from "dbus-next";
import { DEBUG, debug } from "../debug";
import type { Logger } from "../RemoteLogger";

const SERVICE = "org.exiled.ExiledExchange2";
const OBJECT = "/Tracker";
const IFACE = "org.exiled.ExiledExchange2.Tracker";

function buildKwinScript(shortcuts: string[]): string {
  // Embed the shortcut list as a JSON literal the script can iterate.
  const shortcutsJson = JSON.stringify(shortcuts);
  return `// auto-generated by Exiled Exchange 2
const SERVICE = "${SERVICE}";
const OBJECT = "${OBJECT}";
const IFACE = "${IFACE}";

function isPoeWindow(w) {
  if (!w) return false;
  const cap = w.caption || "";
  const cls = (w.resourceClass || "").toLowerCase();
  return cap === "Path of Exile 2" || cls === "steam_app_2694490";
}

function call(method) {
  const args = Array.prototype.slice.call(arguments, 1);
  callDBus.apply(null, [SERVICE, OBJECT, IFACE, method].concat(args));
}

function emitGeometry(w) {
  const g = w.frameGeometry;
  if (!g) return;
  call("Geometry", g.x | 0, g.y | 0, g.width | 0, g.height | 0);
}

function trackPoe(w) {
  call("Present", true);
  emitGeometry(w);
  call("Focus", !!w.active);
  if (w.frameGeometryChanged) {
    w.frameGeometryChanged.connect(function () { emitGeometry(w); });
  }
  // Listen for PoE2's own active state changes. This is more reliable
  // than workspace.windowActivated (which fires for ANY window becoming
  // active and can leave us in the wrong state when intermediate windows
  // — notifications, daemons, our own proxy — briefly take focus
  // without KWin emitting a clean re-activation for PoE2 afterwards).
  if (w.activeChanged) {
    w.activeChanged.connect(function () {
      call("Focus", !!w.active);
    });
  }
  if (w.closed) {
    w.closed.connect(function () { call("Present", false); });
  }
}

call("Hello", "tracker loaded");

// Inventory pass
var list = workspace.windowList ? workspace.windowList() : workspace.clientList();
for (var i = 0; i < list.length; i++) {
  if (isPoeWindow(list[i])) { trackPoe(list[i]); break; }
}

// PoE2 appearing later
var added = workspace.windowAdded || workspace.clientAdded;
if (added) {
  added.connect(function (w) { if (isPoeWindow(w)) trackPoe(w); });
}

// Focus tracking is done per-PoE-window via w.activeChanged inside
// trackPoe (see comment there for why workspace-level activation events
// proved unreliable).

// Cursor position feed. uiohook doesn't see mousemove while PoE2 owns the
// pointer (KWin doesn't forward to XWayland), and Electron's
// screen.getCursorScreenPoint() returns frozen coords there. KWin's JS
// sandbox has no setInterval / Qt globals, so we hook the workspace's
// cursorPosChanged signal and push live coords to our DBus service.
if (workspace.cursorPosChanged) {
  var lastCursorX = -1;
  var lastCursorY = -1;
  workspace.cursorPosChanged.connect(function () {
    var pos = workspace.cursorPos;
    if (!pos) return;
    var x = pos.x | 0;
    var y = pos.y | 0;
    if (x !== lastCursorX || y !== lastCursorY) {
      lastCursorX = x;
      lastCursorY = y;
      call("CursorPos", x, y);
    }
  });
}

// User-configured hotkeys. KWin's registerShortcut binds at the compositor
// level, which is the only way Ctrl+letter combos make it through under KDE
// Wayland (KWin filters them out of the XWayland pipeline otherwise).
var SHORTCUTS = ${shortcutsJson};
for (var j = 0; j < SHORTCUTS.length; j++) {
  (function (shortcut, idx) {
    registerShortcut(
      "exiled-exchange-2-hk-" + idx,
      "Exiled Exchange 2: " + shortcut,
      shortcut,
      function () { call("Hotkey", shortcut); }
    );
  })(SHORTCUTS[j], j);
}
`;
}

export interface Bounds {
  x: number;
  y: number;
  width: number;
  height: number;
}

export function isKdeWayland(): boolean {
  return (
    process.platform === "linux" &&
    !!process.env.WAYLAND_DISPLAY &&
    (process.env.XDG_CURRENT_DESKTOP || "")
      .toUpperCase()
      .includes("KDE")
  );
}

export class WaylandTracker extends EventEmitter {
  private _bounds: Bounds | null = null;
  private _focused = false;
  private _present = false;
  private _cursor: { x: number; y: number } | null = null;
  // TEMP debug
  _cursorLogCount: number | undefined = undefined;
  private _shortcuts: string[] = [];
  // When pauseShortcuts() is called we stash the active list here and
  // reload the script with no registrations, so KWin stops grabbing
  // those keys at the compositor level. resumeShortcuts() restores.
  // While paused, setShortcuts updates this instead of triggering a
  // reload (we still want the new list applied — just not until resume).
  private _pausedShortcuts: string[] | null = null;
  private bus: dbus.MessageBus | null = null;
  private scriptPath: string | null = null;
  private scriptId: number | null = null;
  private reloading = false;
  // start() returns this promise on the second+ call so callers don't
  // double-init. setShortcuts() awaits it so the initial script load and
  // any concurrent reloads don't race on the script file / KWin's loadScript.
  private _startPromise: Promise<void> | null = null;

  constructor(private logger: Logger) {
    super();
  }

  get bounds(): Bounds | null {
    return this._bounds;
  }
  get focused(): boolean {
    return this._focused;
  }
  get present(): boolean {
    return this._present;
  }
  get cursor(): { x: number; y: number } | null {
    return this._cursor;
  }

  async start(): Promise<void> {
    if (this._startPromise) return this._startPromise;
    this._startPromise = this._doStart();
    return this._startPromise;
  }

  private async _doStart(): Promise<void> {
    debug("[WaylandTracker] start: registering DBus...");
    await this.registerDbus();
    debug("[WaylandTracker] DBus registered, loading KWin script...");
    await this.loadKwinScript();
    debug(
      `[WaylandTracker] KWin script loaded, id=${this.scriptId}, path=${this.scriptPath}`,
    );
    this.logger.write(
      `info [WaylandTracker] started, scriptId=${this.scriptId}`,
    );
  }

  async stop(): Promise<void> {
    await this.unloadKwinScript();
    if (this.scriptPath) {
      await fs.unlink(this.scriptPath).catch(() => {});
    }
    if (this.bus) {
      try {
        this.bus.disconnect();
      } catch {
        /* noop */
      }
    }
  }

  // Replace the registered hotkeys. Reloads the KWin script so the new set
  // takes effect. Cheap because the script is short and KWin's loadScript is
  // a couple of DBus calls.
  async setShortcuts(shortcuts: string[]): Promise<void> {
    const sorted = [...shortcuts].sort();
    debug(
      `[WaylandTracker] setShortcuts called with ${sorted.length}: ${JSON.stringify(sorted)}`,
    );
    if (this._pausedShortcuts !== null) {
      // Currently paused — stash the new list and apply on resume.
      this._pausedShortcuts = sorted;
      debug("[WaylandTracker] setShortcuts: paused, stash for resume");
      return;
    }
    if (
      sorted.length === this._shortcuts.length &&
      sorted.every((s, i) => s === this._shortcuts[i])
    ) {
      debug("[WaylandTracker] setShortcuts: unchanged, skip");
      return;
    }
    await this.applyShortcutsReload(sorted);
  }

  // Temporarily release every KGlobalAccel registration we hold so the
  // user can type those keys (F5, Ctrl+D, Ctrl+Space, ...) into the
  // settings UI's HotkeyInput fields. Without this, KWin intercepts the
  // key at the compositor level — our handler fires and bails (isActive
  // is false because the panel is up), and the keypress never reaches
  // the InputProxy, so HotkeyInput's @keyup capture sees nothing.
  //
  // Called from OverlayWindow when InputProxy is shown.
  async pauseShortcuts(): Promise<void> {
    if (this._pausedShortcuts !== null) return;
    debug("[WaylandTracker] pauseShortcuts");
    this._pausedShortcuts = this._shortcuts;
    await this.applyShortcutsReload([]);
  }

  async resumeShortcuts(): Promise<void> {
    if (this._pausedShortcuts === null) return;
    debug("[WaylandTracker] resumeShortcuts");
    const restored = this._pausedShortcuts;
    this._pausedShortcuts = null;
    await this.applyShortcutsReload(restored);
  }

  // The reload path used by both setShortcuts and pause/resume. Skips
  // the diff check and the paused-state guard that setShortcuts uses.
  private async applyShortcutsReload(target: string[]): Promise<void> {
    this._shortcuts = [...target].sort();
    if (this._startPromise) {
      await this._startPromise.catch(() => {});
    }
    if (!this.bus) {
      debug("[WaylandTracker] applyShortcutsReload: bus not ready");
      return;
    }
    if (this.reloading) {
      debug("[WaylandTracker] applyShortcutsReload: already reloading, drop");
      return;
    }
    this.reloading = true;
    try {
      // Explicitly unregister every previously-held action. KWin doesn't
      // clean up KGlobalAccel registrations on script unload, so without
      // this the on-disk + in-memory grabs survive and silently block
      // the new (potentially-empty) set from taking effect.
      await this.clearPriorShortcuts();
      await this.unloadKwinScript();
      await this.loadKwinScript();
      debug(
        `[WaylandTracker] applyShortcutsReload: scriptId=${this.scriptId} with ${this._shortcuts.length} shortcuts`,
      );
    } finally {
      this.reloading = false;
    }
  }

  // Unregister every exiled-exchange-2-* action currently held by the
  // kwin component. Used by applyShortcutsReload to ensure stale grabs
  // from prior reloads / prior process runs don't survive into the new
  // registration cycle.
  private async clearPriorShortcuts(): Promise<void> {
    if (!this.bus) return;
    try {
      const compObj = await this.bus.getProxyObject(
        "org.kde.kglobalaccel",
        "/component/kwin",
      );
      const compIface = compObj.getInterface(
        "org.kde.kglobalaccel.Component",
      );
      const names = (await compIface.shortcutNames()) as string[];
      const ours = names.filter((n) => n.startsWith("exiled-exchange-2-"));
      if (ours.length === 0) return;
      const accelObj = await this.bus.getProxyObject(
        "org.kde.kglobalaccel",
        "/kglobalaccel",
      );
      const accelIface = accelObj.getInterface("org.kde.KGlobalAccel");
      for (const name of ours) {
        await accelIface.unregister("kwin", name).catch(() => {});
      }
      debug(`[WaylandTracker] clearPriorShortcuts: unregistered ${ours.length}`);
    } catch (err) {
      debug(
        `[WaylandTracker] clearPriorShortcuts failed: ${(err as Error).message}`,
      );
    }
  }

  // For each desired shortcut, ask KGlobalAccel who currently holds that key
  // and call setShortcut(actionId, [], 0) to release it. Used to pry the
  // binding away from other Electron apps (Discord's "Toggle Deafen" on
  // Ctrl+D etc.) before our KWin script claims it. The displaced app will
  // re-register on its next launch / config edit, but during our run we own
  // the binding.
  private async registerDbus(): Promise<void> {
    this.bus = dbus.sessionBus();
    const tracker = this;

    class TrackerInterface extends dbus.interface.Interface {
      Geometry(x: number, y: number, w: number, h: number) {
        tracker._setGeometry({ x, y, width: w, height: h });
      }
      Focus(focused: boolean) {
        tracker._setFocus(focused);
      }
      Present(present: boolean) {
        tracker._setPresent(present);
      }
      Hello(msg: string) {
        tracker.logger.write(
          `info [WaylandTracker] KWin script hello: ${msg}`,
        );
      }
      Hotkey(shortcut: string) {
        tracker.emit("hotkey", shortcut);
      }
      CursorPos(x: number, y: number) {
        if (
          DEBUG &&
          (tracker._cursorLogCount = (tracker._cursorLogCount ?? 0) + 1) %
            20 ===
            0
        ) {
          console.log(`[WaylandTracker] CursorPos x=${x} y=${y}`);
        }
        tracker._cursor = { x, y };
      }
    }

    (TrackerInterface as unknown as {
      configureMembers: (cfg: unknown) => void;
    }).configureMembers({
      methods: {
        Geometry: { inSignature: "iiii", outSignature: "" },
        Focus: { inSignature: "b", outSignature: "" },
        Present: { inSignature: "b", outSignature: "" },
        Hello: { inSignature: "s", outSignature: "" },
        Hotkey: { inSignature: "s", outSignature: "" },
        CursorPos: { inSignature: "ii", outSignature: "" },
      },
    });

    const iface = new TrackerInterface(IFACE);
    this.bus.export(OBJECT, iface);
    await this.bus.requestName(SERVICE, 0);
  }

  private async loadKwinScript(): Promise<void> {
    this.scriptPath = path.join(
      app.getPath("userData"),
      "kwin-poe-tracker.js",
    );
    await fs.writeFile(this.scriptPath, buildKwinScript(this._shortcuts));

    if (!this.bus) throw new Error("DBus not connected");
    const scriptingObj = await this.bus.getProxyObject(
      "org.kde.KWin",
      "/Scripting",
    );
    const scripting = scriptingObj.getInterface("org.kde.kwin.Scripting");
    const loaded = await scripting.loadScript(this.scriptPath);
    this.scriptId =
      typeof loaded === "number"
        ? loaded
        : typeof (loaded as { value?: number }).value === "number"
          ? (loaded as { value: number }).value
          : Number(loaded);

    const scriptObj = await this.bus.getProxyObject(
      "org.kde.KWin",
      `/Scripting/Script${this.scriptId}`,
    );
    const script = scriptObj.getInterface("org.kde.kwin.Script");
    await script.run();
  }

  private async unloadKwinScript(): Promise<void> {
    if (!this.bus || this.scriptId === null || !this.scriptPath) return;
    try {
      const scriptObj = await this.bus.getProxyObject(
        "org.kde.KWin",
        `/Scripting/Script${this.scriptId}`,
      );
      const scriptIface = scriptObj.getInterface("org.kde.kwin.Script");
      await scriptIface.stop().catch(() => {});

      const scriptingObj = await this.bus.getProxyObject(
        "org.kde.KWin",
        "/Scripting",
      );
      const scriptingIface = scriptingObj.getInterface(
        "org.kde.kwin.Scripting",
      );
      await scriptingIface.unloadScript(this.scriptPath).catch(() => {});
    } catch (err) {
      this.logger.write(
        `warn [WaylandTracker] script unload failed: ${(err as Error).message}`,
      );
    }
    this.scriptId = null;
  }

  private _setGeometry(b: Bounds) {
    this._bounds = b;
    this.emit("geometry", b);
  }

  private _setFocus(focused: boolean) {
    if (this._focused === focused) return;
    this._focused = focused;
    this.emit("focus", focused);
  }

  private _setPresent(present: boolean) {
    if (this._present === present) return;
    this._present = present;
    this.emit("present", present);
  }
}
